### ISSUE TITLE
tr-ime-debug.el, tr-ime-hook.el, tr-ime-font.el, tr-ime-isearch.el are missing.

### ISSUE THREAD

**Issue by KatsuhisaHiguchi** [trueroad/tr-emacs-ime-module#10]
Regarding tr-ime-20211120, it looks that some necessary files are not included. 
As result of it, emacs doesn't work as I expected (at least on my env. )
Those missing files are tr-ime-debug.el, tr-ime-hook.el, tr-ime-font.el, tr-ime-isearch.el.
It is possible that I misunderstand handling of the package or the packaging system.
Please fix it or correct my misunderstanding.

**Comment by trueroad** [comment]
Did you install tr-ime from Melpa?
I've checked the archive of the latest version tr-ime-20211120.718 registered in Melpa, then all the files you mentioned are contained.
In other words, there is nothing wrong with the package.
For more information on how to use the package system, please find and read the documentation on Melpa.
