### ISSUE TITLE
Change foreground/background color of frame

### ISSUE THREAD

**Issue by archiif** [trueroad/tr-emacs-ime-module#11]
You can already change the font by setting `ime-font`, but is there a way to change the foreground/background color so that it matches our personal theme colors?
![image](https://user-images.githubusercontent.com/60074051/166075013-e9904cbf-5782-48e1-8604-cadc34be2689.png)

**Comment by trueroad** [comment]
IME composition string is not rendered by Emacs or tr-ime but IME itself.
tr-ime uses ImmSetCompositionFont() API to set the font for the composition string.
But, it cannot set the color.

If I understand correctly, no other IMM APIs seem to allow color settings.
https://docs.microsoft.com/en-us/windows/win32/intl/input-method-manager-functions

**Comment by archiif** [comment]
I see. I'm curious how other applications handle this though. Editors like Vim seem to be able to match the background color of the composition window (maybe with transparency?) with the editor out-of-the-box, how does it achieve this?

**Comment by trueroad** [comment]
I don't know how Vim achieves it.
If I understand correctly, Microsoft Word achieves it by rendering the composition string by itself, not by the IME.
It is very difficult to achieve that with tr-ime.
