### ISSUE TITLE
(boundp 'tr-ime-enabled-features) was nil

### ISSUE THREAD

**Issue by melito00** [trueroad/tr-emacs-ime-module#5]
(fboundp 'tr-ime-advanced-install) は t を返すのでモジュールの配置と load-path の設定は問題ないと思いますが、以下の設定を入れても (boundp 'tr-ime-enabled-features) が nil になります。
```
(require 'tr-ime nil t)
(when (fboundp 'tr-ime-advanced-install)
  (tr-ime-advanced-install))
```

**Comment by trueroad** [comment]
リリース版の ver. 0.4.0 ごご利用でしょうか？変数 tr-ime-enabled-features を導入したのは ver. 0.4.0 のリリースより後の 93f001dbb6569adaef7e6bf3a34a716b24c99b45 になるので、リリース版をお使いの場合にはご指摘のような事象になります。

リリース版 ver. 0.4.0 での環境判定方法は、zipファイルに同梱している README.md をご覧いただくか、リリースのタグを打ってある
https://github.com/trueroad/tr-emacs-ime-module/tree/v0.4.0
でご覧いただくと良いと思います。

次期リリースは変数 tr-ime-enabled-features を導入したものにするつもりですので、そちらの方がよいということであれば、`.el` をインストールしていただいているフォルダへ、本リポジトリの最新の lisp ディレクトリ（2020年11月7日現在では https://github.com/trueroad/tr-emacs-ime-module/tree/57d4c3dde5c18c04e4f5c3006310d0fb95daf312/lisp ）にある `.el` ファイルで上書きすれば、変数 tr-ime-enabled-features が使えるようになると思います。2020年11月7日現在、モジュールDLLはリリース版 ver. 0.4.0 から変更していませんので、`.el` だけ最新のものに置き換えれば更新できます。

**Comment by melito00** [comment]
リリース版を利用しました。リポジトリから .el を上書きして利用します。
