### ISSUE TITLE
fail to byte-compile tr-ime-prefix-key.el

### ISSUE THREAD

**Issue by ikazuhiro** [trueroad/tr-emacs-ime-module#6]
Because `tr-ime-enabled-features` is defined without initial value in `tr-ime-openstatus.el`, loading `tr-ime-openstatus.el` is failed without `tr-ime.el`, in which `tr-ime-enabled-features` is defined with initial value.  I think it is not good that a variable is defined at multiple places (as different initial values).

**Comment by trueroad** [comment]
Thanks. I've fixed.
