### ISSUE TITLE
Fail to byte-compile tr-ime-documentfeed.el in terminal

### ISSUE THREAD

**Issue by ikazuhiro** [trueroad/tr-emacs-ime-module#7]
Loading `tr-ime-reconversion.el` fails in terminal.  The reason is that `tr-ime-reconversion--set` fails in terminal (`(frame-parameter nil 'window-id)` returns `nil` in termianl).  The function is called in defining `tr-ime-reconversion-p`.

**Comment by trueroad** [comment]
Thanks. I've fixed.
