### ISSUE TITLE
IMEオンでの \C-m の入力

### ISSUE THREAD

**Issue by ukundo** [trueroad/tr-emacs-ime-module#8]
入力を確定し、改行してほしいが、現状よくわからないエラーなってしまいます。

**Comment by trueroad** [comment]
それは、未確定文字列が「こんにちは」になっているときに C-m で確定させると、`*Messages*` に

```
C-こ is undefined
C-ん is undefined
C-に is undefined
C-ち is undefined
C-は is undefined
```

が出て確定文字列にならないという症状でしょうか？
それであれば tr-ime の問題ではなく、Emacs 本体の問題です（tr-ime 無しの、素の Emacs 27.1 で発生します）。
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44641
https://emba.gnu.org/emacs/emacs/-/commit/86cbc9d216c724e6be5db27fb33df2ca0c7d9804
Emacs 27.1.91 では修正されています。

**Comment by ukundo** [comment]
なるほど、納得しました。
丁寧な対応ありがとうございました。
次のリリースを待ってみます。
