### ISSUE TITLE
Fail to load tr-ime-hook.el

### ISSUE THREAD

**Issue by ikazuhiro** [trueroad/tr-emacs-ime-module#9]
The below code in `lisp/tr-ime-hook.el` raises an error on master (probably and emacs-28) branch.
```elisp
(define-obsolete-variable-alias 'select-window-functions
  'tr-ime-hook-select-window-functions "2020")

-> Cannot make an internal variable an alias
```

**Comment by trueroad** [comment]
On emacs-28.0.50-snapshot-2021-01-15, tr-ime works fine.
https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/

Is your emacs IME patched?
If so, which patch do you use?

When tr-ime detects an IME patch, it will stop working to prevent conflicts.
I suspect that tr-ime is failing to detect the IME patch you are using.

**Comment by ikazuhiro** [comment]
Ah, I used Emacs with IME patch.  I intended build Emacs with `--without-w32-ime`, but it has W32-IME feature by mistake.  When I surely build Emacs with `--without-w32-ime`, your module works correctly on master branch.  Sorry for the noise.
